# Generated by Django 3.2.16 on 2023-01-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0008_add_semantic_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordform",
            name="rw_domains",
        ),
        migrations.RemoveField(
            model_name="wordform",
            name="rw_indices",
        ),
        migrations.RemoveField(
            model_name="wordform",
            name="wn_synsets",
        ),
        migrations.CreateModel(
            name="WordNet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "synset",
                    models.CharField(
                        help_text="WordNet synset classification", max_length=2048
                    ),
                ),
                (
                    "hypernyms",
                    models.ManyToManyField(
                        related_name="_lexicon_wordnet_hypernyms_+",
                        to="lexicon.WordNet",
                    ),
                ),
                (
                    "hyponyms",
                    models.ManyToManyField(
                        related_name="_lexicon_wordnet_hyponyms_+", to="lexicon.WordNet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapidWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="The domain of this class", max_length=2048
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        help_text="The index of this class", max_length=64
                    ),
                ),
                (
                    "hypernyms",
                    models.ManyToManyField(
                        related_name="_lexicon_rapidwords_hypernyms_+",
                        to="lexicon.RapidWords",
                    ),
                ),
                (
                    "hyponyms",
                    models.ManyToManyField(
                        related_name="_lexicon_rapidwords_hyponyms_+",
                        to="lexicon.RapidWords",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wordform",
            name="rw_classes",
            field=models.ManyToManyField(to="lexicon.RapidWords"),
        ),
        migrations.AddField(
            model_name="wordform",
            name="wn_synsets",
            field=models.ManyToManyField(to="lexicon.WordNet"),
        ),
    ]
