# Generated by Django 3.2.16 on 2023-02-07 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lexicon", "0014_add_serializers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordform",
            name="rw_classes",
        ),
    ]
